use self_serve;

UPDATE `action` SET `response_definition` = '{ \"entityResponseTranslator\": \"var ApiResponse = function(_status, _message) { this.status = _status; this.message = _message; }; function translate(responseData) { try { var responseIntermediate = JSON.parse(responseData); var response = JSON.parse(responseIntermediate); if (response.status === \\\"completed\\\") { return new ApiResponse(\\\"SUCCESS\\\", \\\"Successfully processed \\\" + response.processedRecords + \\\" rows out of \\\" + response.totalRecords + \\\" rows\\\"); } else if (response.status === \\\"empty\\\") { return new ApiResponse(\\\"ERROR_STOP\\\", \\\"No records found to add agents\\\"); } else if (response.status === \\\"upload_error\\\") { return new ApiResponse(\\\"ERROR_STOP\\\", \\\"Some erroneous records were identified during the last operation. Please click on View Configurations for details.\\\"); } else if (response.status === \\\"validation_error\\\") { return new ApiResponse(\\\"ERROR_STOP\\\", \\\"Validation errors were identified during the last operation. Please click on View Configurations for details.\\\"); } else return new ApiResponse(\\\"ERROR\\\", JSON.stringify(response)) } catch (e) { return new ApiResponse(\\\"ERROR\\\", \\\"Error while processing your request\\\"); } }\" }' 
WHERE (`id` = '53');

UPDATE `action` SET `response_definition` = '{ \"entityResponseTranslator\": \"var ApiResponse = function(_status, _message) { this.status = _status; this.message = _message; }; function translate(responseData) { try { var responseIntermediate = JSON.parse(responseData); var response = JSON.parse(responseIntermediate); if (response.status === \\\"completed\\\") { return new ApiResponse(\\\"SUCCESS\\\", \\\"Successfully processed \\\" + response.processedRecords + \\\" rows out of \\\" + response.totalRecords + \\\" rows\\\"); } else if (response.status === \\\"empty\\\") { return new ApiResponse(\\\"ERROR_STOP\\\", \\\"No records found to add agents\\\"); } else if (response.status === \\\"upload_error\\\") { return new ApiResponse(\\\"ERROR_STOP\\\", \\\"Some erroneous records were identified during the last operation. Please click on View Configurations for details.\\\"); } else if (response.status === \\\"validation_error\\\") { return new ApiResponse(\\\"ERROR_STOP\\\", \\\"Validation errors were identified during the last operation. Please click on View Configurations for details.\\\"); } else return new ApiResponse(\\\"ERROR\\\", JSON.stringify(response)) } catch (e) { return new ApiResponse(\\\"ERROR\\\", \\\"Error while processing your request\\\"); } }\" }' 
WHERE (`id` = '55');

UPDATE `activity_template` SET `entity_location` = '{\"BULK\": {\"entityIdLocation\": \"createBulkAgentsTest_p0.accountId\", \"entityLabelLocation\": \"createBulkAgentsTest_p0.accountId\"}, \"CREATE\": {\"entityIdLocation\": \"createUserTest_p0.tabsField.0.userName\", \"entityLabelLocation\": \"createUserTest_p0.tabsField.0.userName\"}, \"UPDATE\": {\"entityIdLocation\": \"updateUserTest_p0.tabsField.0.key\", \"entityLabelLocation\": \"updateUserTest_p0.tabsField.0.userName\"}}' 
WHERE (`id` = 'userTest');

UPDATE `activity_template` SET `entity_location` = '{\"BULK\": {\"entityIdLocation\": \"createBulkAgentsLive_p0.accountId\", \"entityLabelLocation\": \"createBulkAgentsLive_p0.accountId\"}, \"CREATE\": {\"entityIdLocation\": \"createUserLive_p0.tabsField.0.userName\", \"entityLabelLocation\": \"createUserLive_p0.tabsField.0.userName\"}, \"UPDATE\": {\"entityIdLocation\": \"updateUserLive_p0.tabsField.0.key\", \"entityLabelLocation\": \"updateUserLive_p0.tabsField.0.userName\"}}' 
WHERE (`id` = 'userLive');
