use self_serve;

-- CENTRAL-7949: Disabling outbound entities and handling outbound account configs
ALTER TABLE `fetch_config_template`
ADD COLUMN `execution_order` INT(10) NULL DEFAULT 0 AFTER `service_id`;

-- Updated as part of hotfix for CLOUD-93961 and AP-630

INSERT INTO `fetch_config_template` (`id`,`created_by`,`created_on`,`last_updated_by`,`last_updated_on`,`fetch_for`,`headers`,`params`,`relativeurl`,`resp_api_to_resp_ui`,`translator_type`,`type`,`service_id`) VALUES
(70,'default.user','2021-05-21 12:24:46.000000','default.user','2021-05-21 12:24:46.000000','getBulkAgentsErrorExcel','{\"referer\": \"https://salesdemo.portal.assist.staging.247-inc.net\", \"GenerateAuthToken\": \"Bearer \"}','{\"contexts\": [\"accountId\", \"clientId\", \"componentAccountId\", \"componentClientId\"], \"constants\": {}}','/en/hierarchy/rest/clients/${componentClientId}/accounts/${componentAccountId}/agents/upload/failedrecords','{\"objectTranslator\": \"function translate(apiData) { return apiData; }\"}','NONE','PAGE_DATA_VALUE','assist');

-- CENTRAL-7949: Disabling outbound entities and handling outbound account configs

INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('71', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2021-06-13 12:24:46.000000', 'createPropertyConfig_p0', '{\"GenerateAuthToken\": \"Bearer \"}', '{\"contexts\": [\"accountId\", \"clientId\", \"componentAccountId\", \"componentClientId\"], \"constants\": {}}', '/en/hierarchy/rest/clients/${componentClientId}/accounts/${componentAccountId}/clientstartupconfig/NEMO_outboundMessageEnabled', '{\"objectTranslator\": \"function translate(apiData) { var result = JSON.parse(apiData); var uiData ={}; uiData.outboundEnabled = result.configValue; return JSON.stringify(uiData); }\"}', 'JS', 'PAGE_DATA_VALUE', 'assist', '0');
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('72', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2021-06-13 12:24:46.000000', 'updatePropertyConfig_p0', '{\"GenerateAuthToken\": \"Bearer \"}', '{\"contexts\": [\"accountId\", \"clientId\", \"componentAccountId\", \"componentClientId\"], \"constants\": {}}', '/en/hierarchy/rest/clients/${componentClientId}/accounts/${componentAccountId}/clientstartupconfig/NEMO_outboundMessageEnabled', '{\"objectTranslator\": \"function translate(apiData) { var result = JSON.parse(apiData); var uiData ={}; uiData.outboundEnabled = result.configValue; return JSON.stringify(uiData); }\"}', 'JS', 'PAGE_DATA_VALUE', 'assist', '0');
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('73', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2021-06-13 12:24:46.000000', 'listProperty', '{\"GenerateAuthToken\": \"Bearer \"}', '{\"contexts\": [\"clientId\", \"accountId\", \"componentClientId\", \"componentAccountId\"], \"constants\": {}}', '/en/hierarchy/rest/clients/${componentClientId}/accounts/${componentAccountId}/clientstartupconfig/NEMO_outboundMessageEnabled', '{\"objectTranslator\": \"function translate(apiData) { var result = JSON.parse(apiData); var uiData ={}; uiData.outboundEnabled = result.configValue; return JSON.stringify(uiData); }\"}', 'JS', 'AUXILIARY_RESPONSE', 'assist', '0');

/* Skill level Id mapping in user to skills mapping*/
/* updateUserTest */

INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('74', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'updateUserTest_p0', '{}', '{\"contexts\": [\"componentAccountId\", \"clientId\", \"accountId\", \"componentClientId\", \"entity\"], \"constants\": {}}', '/en/admin/rest/ohs/listByAccount?entityType=skill&accountId=${componentAccountId}', '{\"objectTranslator\": \"function translate(apiData) { try { var uiData = { \\\"tabsField\\\": [{}, {}, {}] }; var values = JSON.parse(apiData); var list = JSON.parse(values.data.list); var t1 = uiData.tabsField[1]; var data = []; list.forEach(function (items) { var skillLevels = { skillId: items.entityBaseData.entityId, skillLevel: items.entityAttributes.skillLevel }; data.push(skillLevels); }); t1.skillLevels = data; return JSON.stringify(uiData); } catch (e) {} return null; }\"}', 'JS', 'PAGE_DATA_VALUE', 'assist', '0');
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('75', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'updateUserTest_p0', '{}', '{\"contexts\": [\"componentAccountId\", \"clientId\", \"accountId\", \"componentClientId\", \"entity\"], \"constants\": {}}', '/en/admin/rest/ohs/listByAccount?entityType=skill&accountId=${componentAccountId}', '{\"objectTranslator\": \"function translate(apiData) { try { var values = JSON.parse(apiData); var list = JSON.parse(values.data.list); var data = []; list.forEach(function (items) { var skillLevel = { skillId: items.entityBaseData.entityId, skillLevel: items.entityAttributes.skillLevel }; data.push(skillLevel); }); return JSON.stringify(data); } catch (e) {} return null; }\"}', 'JS', 'AUXILIARY_RESPONSE', 'assist', '0');

/* updateUserLive */
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('76', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'updateUserLive_p0', '{}', '{\"contexts\": [\"componentAccountId\", \"clientId\", \"accountId\", \"componentClientId\", \"entity\"], \"constants\": {}}', '/en/admin/rest/ohs/listByAccount?entityType=skill&accountId=${componentAccountId}', '{\"objectTranslator\": \"function translate(apiData) { try { var uiData = { \\\"tabsField\\\": [{}, {}, {}] }; var values = JSON.parse(apiData); var list = JSON.parse(values.data.list); var t1 = uiData.tabsField[1]; var data = []; list.forEach(function (items) { var skillLevels = { skillId: items.entityBaseData.entityId, skillLevel: items.entityAttributes.skillLevel }; data.push(skillLevels); }); t1.skillLevels = data; return JSON.stringify(uiData); } catch (e) {} return null; }\"}', 'JS', 'PAGE_DATA_VALUE', 'assist', '0');
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('77', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'updateUserLive_p0', '{}', '{\"contexts\": [\"componentAccountId\", \"clientId\", \"accountId\", \"componentClientId\", \"entity\"], \"constants\": {}}', '/en/admin/rest/ohs/listByAccount?entityType=skill&accountId=${componentAccountId}', '{\"objectTranslator\": \"function translate(apiData) { try { var values = JSON.parse(apiData); var list = JSON.parse(values.data.list); var data = []; list.forEach(function (items) { var skillLevel = { skillId: items.entityBaseData.entityId, skillLevel: items.entityAttributes.skillLevel }; data.push(skillLevel); }); return JSON.stringify(data); } catch (e) {} return null; }\"}', 'JS', 'AUXILIARY_RESPONSE', 'assist', '0');

/* createUserTest */
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('78', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'createUserTest_p0', '{}', '{\"contexts\": [\"componentAccountId\", \"clientId\", \"accountId\", \"componentClientId\", \"entity\"], \"constants\": {}}', '/en/admin/rest/ohs/listByAccount?entityType=skill&accountId=${componentAccountId}', '{\"objectTranslator\": \"function translate(apiData) { try { var uiData = { \\\"tabsField\\\": [{}, {}, {}] }; var values = JSON.parse(apiData); var list = JSON.parse(values.data.list); var t1 = uiData.tabsField[1]; var data = []; list.forEach(function (items) { var skillLevels = { skillId: items.entityBaseData.entityId, skillLevel: items.entityAttributes.skillLevel }; data.push(skillLevels); }); t1.skillLevels = data; return JSON.stringify(uiData); } catch (e) {} return null; }\"}', 'JS', 'PAGE_DATA_VALUE', 'assist', '0');

/* createUserLive */
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`)
VALUES ('79', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'createUserLive_p0', '{}', '{\"contexts\": [\"componentAccountId\", \"clientId\", \"accountId\", \"componentClientId\", \"entity\"], \"constants\": {}}', '/en/admin/rest/ohs/listByAccount?entityType=skill&accountId=${componentAccountId}', '{\"objectTranslator\": \"function translate(apiData) { try { var uiData = { \\\"tabsField\\\": [{}, {}, {}] }; var values = JSON.parse(apiData); var list = JSON.parse(values.data.list); var t1 = uiData.tabsField[1]; var data = []; list.forEach(function (items) { var skillLevels = { skillId: items.entityBaseData.entityId, skillLevel: items.entityAttributes.skillLevel }; data.push(skillLevels); }); t1.skillLevels = data; return JSON.stringify(uiData); } catch (e) {} return null; }\"}', 'JS', 'PAGE_DATA_VALUE', 'assist', '0');

/* CENTRAL: 8140 : Active Cards: Filter already configured active cards from dropdown */
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`) VALUES ('80', 'default.user', '2020-10-15 12:24:56.000000', 'Arul.Abirami.S@247-inc.com', '2021-09-01 10:41:36.880259', 'listFilteredActiveCards', '{\"GenerateAuthToken\": \"Bearer \"}', '{\"contexts\": [\"clientId\", \"accountId\", \"componentClientId\", \"componentAccountId\"], \"constants\": {}, \"queryParams\": null}', '/en/hierarchy/rest/clients/${componentClientId}/accounts/${componentAccountId}/smartcommand', '{\"objectTranslator\": \"function translate(values){ try{ values = JSON.parse(values);var entities = {existingCards:[], id:[]}; if (values) {var items = values.data.items; items.forEach(function(item){if(item.commandName.indexOf(\'/f\') !== -1){entities.existingCards.push(item.commandName.replace(\'/f \', \'\'));entities.id.push(item.key);} })} }catch(e){}return JSON.stringify(entities); }\"}', 'JS', 'AUXILIARY_RESPONSE', 'assist', '0');
INSERT INTO `fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`, `execution_order`) VALUES ('81', 'default.user', '2020-10-15 12:24:56.000000', 'uiautomation@247.ai', '2021-05-31 06:48:21.654200', 'listFilteredActiveCards', '{\"apikey\": \"OTRGkEIX1eZGwM75Gs5pYdDnBQ40V7et\"}', '{\"contexts\": [\"clientId\", \"accountId\", \"componentClientId\", \"componentAccountId\"], \"constants\": {}, \"queryParams\": null}', '/crs/v1/clients/${componentClientId}/accounts/${componentAccountId}/activecards/meta?view=live&channel=CHAT', '{\"objectTranslator\": \"function translate(values, entity, context, auxResponse){ try {values = JSON.parse(values); var auxResp = JSON.parse(auxResponse); var existingCards = auxResp.existingCards; var card={enum:[\\\"\\\"], enumNames:[\\\"Select Card\\\"]};var idIndex=-1; if(entity!==null){ auxResp.id.forEach(function(item,index){ if(item===entity){ idIndex=index; } }); }; if (values) {values.forEach(function(item){var count=0;existingCards.forEach(function(data){if(data.toLowerCase()===item.artifactName.toLowerCase()){count=count+1;}});if(count===0){card.enum.push(item.artifactName); card.enumNames.push(item.artifactName); }});}if(idIndex!==-1){card.enum.push(existingCards[idIndex]);card.enumNames.push(existingCards[idIndex]);} }catch (e) { }return JSON.stringify(card); }\"}', 'JS', 'FIELD_OPTIONS', 'VCC', '1');