INSERT INTO `self_serve`.`entity_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `name`) VALUES ('4', 'default.user', '2019-08-08 14:17:12.404294', 'default.user', '2019-08-08 14:17:12.404294', 'teamName');

INSERT INTO `self_serve`.`workflow_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `description`, `model`, `promotion_approval`, `title`, `type`, `entity_template_id` , `entity_location`) VALUES ('createTeams', 'default.user', '2019-08-07 13:50:29.862585', 'default.user', '2019-08-07 13:50:29.862585', 'Create Teams', 'MENU', '', 'Create Teams', 'NON_SINGLETON', '4','createTeams_p0.teamName');

INSERT INTO `self_serve`.`page_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `definition`, `description`, `title`) VALUES ('createTeams_p0', 'default.user', '2019-08-07 14:06:42.713766', 'ravi.b@247-inc.com', '2019-09-18 19:01:07.776838', '{ "schema": { "type": "object", "title": "Create Team", "$schema": "com.tfs/frontends/files/schema/$VERSION/websitetag#", "properties": { "teamName": { "type": "string", "title": "Team Name", "default": "" }, "teamTags": { "type": "array", "items": { "type": "string", "anyOf": [ { "enum": [], "type": "string", "enumNames": [] } ], "title": "Not Selected" }, "title": "Select Tags", "default": [] } }, "description": "Create teams for your client" }, "uiSchema": { "teamName": { "ui:field": "text", "ui:options": { "inputType": "text" } }, "teamTags": { "ui:field": "multiselect", "ui:options": { "inputType": "text" } } }, "fetch": { "list": { "listTag": "teamTags" } ,"page": "createTeams_p0" } }', 'Team creation for Chat', 'Create Teams');

INSERT INTO `self_serve`.`workflow_page` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `page_order`, `section_name`, `page_template_id`, `workflow_template_id`) VALUES ('4', 'default.user', '2019-08-08 14:24:45.621475', 'default.user', '2019-08-08 14:24:45.621475', '1', '', 'createTeams_p0', 'createTeams');

INSERT INTO `self_serve`.`fetch_config_template` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `fetch_for`, `headers`, `params`, `relativeurl`, `resp_api_to_resp_ui`, `translator_type`, `type`, `service_id`) VALUES ('6', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'listTag', '{}', '{"contexts": ["accountId"], "constants": {}}', '/org-hierarchy-service/adminEntity/listByAccount?entityType=tag&accountId=${accountId}-account-default', '{\"objectTranslator\": \"function translate(values){var queues={enum:[], enumNames:[]}; var list=[]; try{values=JSON.parse(values); list=JSON.parse(values.data.list);}catch(e){return e.toString();} list.forEach(function(item){ queues.enum.push(item.entityBaseData.entityId); queues.enumNames.push(item.entityBaseData.entityDisplayName); });return JSON.stringify(queues);}\"}', 'JS', 'FIELD_OPTIONS', 'ohs');

INSERT INTO `action` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `definition`, `description`, `type`) VALUES (4,'default.user','2019-09-19 17:37:31.168947','default.user','2019-09-19 17:37:31.168947','{\"type\": \"REST\", \"method\": \"POST\", \"headers\": {\"Content-Type\": \"application/x-www-form-urlencoded\"}, \"serviceId\": \"ohs\", \"relativePath\": \"/org-hierarchy-service/adminEntity/create?entity=${body}\", \"bodyDefinition\": {}, \"objectTranslator\": \"function translate( pageData, entityId,clientId , accountId, env){ var uiData= JSON.parse(pageData).createTeams_p0; var apiData=[{\\\"entityBaseData\\\":{\\\"accountId\\\": accountId+\\\"-account-default\\\", \\\"clientId\\\": \\\"nemo-client-\\\"+clientId, \\\"entityType\\\": \\\"team\\\" },\\\"entityAttributes\\\": {\\\"teamName\\\": uiData.teamName, \\\"accountId\\\": accountId+\\\"-account-default\\\" }}]; if(uiData.teamTags.join(\\\",\\\")!==\\\"\\\"){ apiData[0].entityAttributes.tags=uiData.teamTags.join(\\\",\\\") }; return JSON.stringify(apiData); }\"}','create team action','REST');

INSERT INTO `self_serve`.`action_workflow` (`id`, `created_by`, `created_on`, `last_updated_by`, `last_updated_on`, `action_id`, `workflow_template_id`) VALUES ('4', 'default.user', '2019-08-27 17:44:15.136579', 'default.user', '2019-08-27 17:44:15.136579', '4', 'createTeams');
