/*CENTRAL-5586: Tags activity*/
USE self_serve;
/*new node group tags*/
INSERT INTO node_group (id, created_by, created_on, last_updated_by, last_updated_on, title, ui_schema) VALUES ('5', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'Tags', '{\"menuGroupName\": \"nav\", \"icon\":\"queueManagementIcon\", \"toolTip\":\"\", \"dashboard\":true, \"display_order\":1, \"isActive\":true}');
INSERT INTO node (id, created_by, created_on, last_updated_by, last_updated_on, node_id, node_type, parent_id) VALUES ('5', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', '5', 'GROUP', '-1');
INSERT INTO menu (id, created_by, created_on, last_updated_by, last_updated_on, menu_group_name, seq, node_id) VALUES ('5', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'nav', '1', '5');
/*reordering the node groups*/
UPDATE node_group SET id = 12 WHERE (id = 2);
UPDATE node_group SET id = 13 WHERE (id = 3);
UPDATE node_group SET id = 14 WHERE (id = 4);
UPDATE node_group SET id = 2 WHERE (id = 5);
UPDATE node_group SET id = 3 WHERE (id = 12);
UPDATE node_group SET id = 4 WHERE (id = 13);
UPDATE node_group SET id = 5 WHERE (id = 14);
/*reordeing the activities inside each node*/
UPDATE node SET parent_id = 5 WHERE (id = 11);
UPDATE node SET parent_id = 4 WHERE (id = 12);
UPDATE node SET parent_id = 5 WHERE (id = 13);
UPDATE node SET parent_id = 4 WHERE (id = 17);
UPDATE node SET parent_id = 3 WHERE (id = 18);
/*Add create and update tags activities*/
INSERT INTO entity_template (id, created_by, created_on, last_updated_by, last_updated_on, fetch_for, name) VALUES ('7', 'default.user', '2019-08-08 14:17:12.404294', 'default.user', '2019-08-08 14:17:12.404294', 'listTag', 'tag');
UPDATE activity_template SET description = 'Tags Activity', entity_location = '{\"CREATE\": \"createTags_p0.tagName\", \"UPDATE\": \"updateTags_p0.tagId\"}', title = 'Tags Configuration', entity_template_id = '7' WHERE (id = 'tags');
INSERT INTO node (id, created_by, created_on, last_updated_by, last_updated_on, node_id, node_type, parent_id) VALUES ('14', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'tags', 'WORKFLOW', '2');
INSERT INTO page_template (id, created_by, created_on, last_updated_by, last_updated_on, definition, description, title, type) VALUES ('createTags_p0', 'default.user', '2019-08-07 14:06:42.713766', 'default.user', '2020-04-16 10:32:50.931044', '{ \"schema\": { \"type\": \"object\", \"properties\": { \"tagName\": { \"type\": \"string\", \"title\": \"Tag Name\", \"default\": \"\" }, \"tagType\": { \"type\": \"string\", \"title\": \"Tag Type\", \"default\": \"\" } } }, \"uiSchema\": { \"tagName\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"fieldSize\": [ 6, 8 ] } }, \"tagType\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"fieldSize\": [ 6, 8 ] } } }, \"viewUiSchema\": { \"tagName\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"isDisabled\": true, \"fieldSize\": [ 6, 8 ] } }, \"tagType\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"isDisabled\": true, \"fieldSize\": [ 6, 8 ] } } }, \"fetch\": { \"page\": \"createTags_p0\" } }', 'Tags creation for chat', 'Create Tags', 'CREATE');
INSERT INTO page_template (id, created_by, created_on, last_updated_by, last_updated_on, definition, description, title, type) VALUES ('updateTags_p0', 'default.user', '2019-08-07 14:06:42.713766', 'default.user', '2020-04-16 10:32:50.931044', '{ \"schema\": { \"type\": \"object\", \"properties\": { \"tagId\": { \"type\": \"string\", \"title\": \"Tag Id\", \"default\": \"\" }, \"tagName\": { \"type\": \"string\", \"title\": \"Tag Name\", \"default\": \"\" }, \"tagType\": { \"type\": \"string\", \"title\": \"Tag Type\", \"default\": \"\" } } }, \"uiSchema\": { \"tagId\": { \"ui:field\": \"plaintext\", \"ui:options\": { \"fieldSize\": [ 6, 8 ] } }, \"tagName\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"fieldSize\": [ 6, 8 ] } }, \"tagType\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"fieldSize\": [ 6, 8 ] } } }, \"viewUiSchema\": { \"tagId\": { \"ui:field\": \"plaintext\", \"ui:options\": { \"isDisabled\": true, \"fieldSize\": [ 6, 8 ] } }, \"tagName\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"isDisabled\": true, \"fieldSize\": [ 6, 8 ] } }, \"tagType\": { \"ui:field\": \"text\", \"ui:options\": { \"inputType\": \"text\", \"isDisabled\": true, \"fieldSize\": [ 6, 8 ] } } }, \"fetch\": { \"page\": \"updateTags_p0\" } }', 'Tags updation for chat', 'Update Tags', 'UPDATE');
UPDATE activity_page SET page_template_id = 'createTags_p0' WHERE (id = '1');
INSERT INTO activity_page (id, created_by, created_on, last_updated_by, last_updated_on, page_order, section_name, page_template_id, activity_template_id) VALUES ('4', 'default.user', '2019-08-07 14:08:14.129995', 'default.user', '2019-08-07 14:08:14.129995', '1', '', 'updateTags_p0', 'tags');
/*fetch configs for tags*/
INSERT INTO fetch_config_template (id, created_by, created_on, last_updated_by, last_updated_on, fetch_for, headers, params, relativeurl, resp_api_to_resp_ui, translator_type, type, service_id) VALUES ('22', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'listTag', '{\"apikey\": \"KtbDtdYYb7EUD4oajYCM8l9Nh7L0AgEc\"}', '{\"contexts\": [\"accountId\"], \"constants\": {}}', '/v1/ohs/adminEntity/listByAccount?entityType=tag&accountId=${accountId}-account-default', '{\"objectTranslator\": \"function translate(values){var entities=[]; var list=[]; try{values=JSON.parse(values); list=JSON.parse(values.data.list);}catch(e){return e.toString();} list.forEach(function(item){ entities.push({name:item.entityBaseData.entityId, label: item.entityBaseData.entityDisplayName}); });return JSON.stringify(entities);}\"}', 'JS', 'ENTITY_LISTING', 'ohs');
INSERT INTO fetch_config_template (id, created_by, created_on, last_updated_by, last_updated_on, fetch_for, headers, params, relativeurl, resp_api_to_resp_ui, translator_type, type, service_id) VALUES ('23', 'default.user', '2019-06-13 12:24:46.000000', 'default.user', '2019-06-13 12:24:46.000000', 'updateTags_p0', '{\"apikey\": \"KtbDtdYYb7EUD4oajYCM8l9Nh7L0AgEc\"}', '{\"contexts\": [\"entity\"], \"constants\": {}}', '/v1/ohs/adminEntity/get?entityId=${entity}&entityType=tag', '{\"objectTranslator\": \"function translate(values) { values = JSON.parse(JSON.parse(values).data.entity); var uiData = {}; uiData.tagId = values.entityBaseData.entityId; uiData.tagName = values.entityAttributes.tagName; uiData.tagType = values.entityAttributes.tagType; return JSON.stringify(uiData); }\"}', 'JS', 'PAGE_DATA_VALUE', 'ohs');
/*create and update tags */
UPDATE action SET definition = '{\"type\": \"REST\", \"method\": \"POST\", \"headers\": {\"apikey\": \"KtbDtdYYb7EUD4oajYCM8l9Nh7L0AgEc\", \"Content-Type\": \"application/x-www-form-urlencoded\"}, \"serviceId\": \"ohs\", \"relativePath\": \"/v1/ohs/adminEntity/update?entity=${body}\", \"bodyDefinition\": {}, \"objectTranslator\": \"function translate(pageData, entityId, clientId, accountId, env) { var uiData = JSON.parse(pageData).updateTags_p0; var apiData = [ { \\\"entityBaseData\\\": { \\\"accountId\\\": accountId + \\\"-account-default\\\", \\\"clientId\\\": \\\"nemo-client-\\\" + clientId, \\\"entityType\\\": \\\"tag\\\", \\\"entityId\\\": entityId, \\\"entityDisplayName\\\": uiData.tagName }, \\\"entityAttributes\\\": { \\\"tagName\\\": uiData.tagName, \\\"tagType\\\": uiData.tagType } } ]; return JSON.stringify(apiData); }\"}', definition_type = 'UPDATE', description = 'Update Tags' WHERE (id = 2);
INSERT INTO action (id, created_by, created_on, last_updated_by, last_updated_on, definition, definition_type, description, type) VALUES ('6', 'default.user', '2019-09-19 17:37:31.168947', 'default.user', '2019-09-19 17:37:31.168947', '{\"type\": \"REST\", \"method\": \"POST\", \"headers\": {\"apikey\": \"KtbDtdYYb7EUD4oajYCM8l9Nh7L0AgEc\", \"Content-Type\": \"application/x-www-form-urlencoded\"}, \"serviceId\": \"ohs\", \"relativePath\": \"/v1/ohs/adminEntity/create?entity=${body}\", \"bodyDefinition\": {}, \"objectTranslator\": \"function translate(pageData, entityId, clientId, accountId, env) { var uiData = JSON.parse(pageData).createTags_p0; var apiData = [ { \\\"entityBaseData\\\": { \\\"accountId\\\": accountId + \\\"-account-default\\\", \\\"clientId\\\": \\\"nemo-client-\\\" + clientId, \\\"entityType\\\": \\\"tag\\\", \\\"entityDisplayName\\\": uiData.tagName }, \\\"entityAttributes\\\": { \\\"tagName\\\": uiData.tagName, \\\"tagType\\\": uiData.tagType } }]; return JSON.stringify(apiData); }\"}', 'CREATE', 'Create tags action', 'REST');
INSERT INTO action_workflow (id, created_by, created_on, last_updated_by, last_updated_on, action_id, activity_template_id) VALUES ('4', 'default.user', '2019-08-27 17:44:15.136579', 'default.user', '2019-08-27 17:44:15.136579', '6', 'tags');
/*update fetch for timezone*/
UPDATE fetch_config_template SET resp_api_to_resp_ui = '{\"objectTranslator\": \"function translate(values) { var timezones = { enum: [], enumNames: [] }; try { values = JSON.parse(values); if (Array.isArray(values)) { timezones.enum = values; timezones.enumNames = values; } } catch (e) { return e.toString(); }; return JSON.stringify(timezones); }\"}' WHERE (id = 4);
/*update entity template name for teams*/
UPDATE entity_template SET name = 'team' WHERE (id = 3);
/*icon for advanced admin*/
UPDATE node_group SET ui_schema = '{\"menuGroupName\": \"nav\", \"icon\":\"adminConsoleIcon\", \"toolTip\":\"\", \"dashboard\":true, \"display_order\":1, \"isActive\":true}' WHERE (id = '5');
